<?php

namespace AppBundle\Repository;

/**
 * fil_messagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class fil_messagesRepository extends \Doctrine\ORM\EntityRepository
{
}
